### ISSUE TITLE
Error when creating a telegram bot

### ISSUE THREAD

**Issue by benthecarman** [alexbosworth/balanceofsatoshis#108]
I used `bos telegram` and entered the api key that the BotFather gave me and received this output

this is version `9.4.1`

```
$ bos telegram

connecting_to_telegram: 
  (empty array)
? Enter Telegram bot API key [hidden]
(node:472477) UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function
    at Object.compactOptions (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/core/helpers/compact.js:11:19)
    at new ApiClient (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/core/network/client.js:208:26)
    at new Telegram (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/telegram.js:7:1)
    at new Telegraf (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/telegraf.js:45:25)
    at asyncAuto.initBot (/usr/local/lib/node_modules/balanceofsatoshis/telegram/start_telegram_bot.js:183:15)
    at runTask (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at readyTasks.push (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31)
    at processQueue (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at result (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17)
    at /usr/local/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at inquirer.prompt.then (/usr/local/lib/node_modules/balanceofsatoshis/telegram/start_telegram_bot.js:124:54)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:472477) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:472477) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by alexbosworth** [comment]
You need to update your node version, version 12 or higher is required
