### ISSUE TITLE
bos forwards --complete throws an error

### ISSUE THREAD

**Issue by smallworlnd** [alexbosworth/balanceofsatoshis#111]
Hello!

Running `bos forwards` works as expected. Running `bos forwards --complete` throws the following error:

```
/usr/local/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /usr/local/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:9:32
    at Object.callback (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/ln-sync/node_modules/lightning/lnd_methods/info/get_node.js:99:20)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client.js:176:36)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /usr/local/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
```

Am I misusing the command?

Running `node` version `v15.14.0`, `bos` version `9.4.1`.

**Comment by alexbosworth** [comment]
I'm not sure that doesn't really make sense

Maybe something else is different between the two calls

**Comment by smallworlnd** [comment]
I thought it strange too since this is just an output formatting thing. Are you asking if I used different options for both commands? If so, I ran the commands exactly as I posted them above. However, if I add either `--out` or `--in` with a pubkey that has been activity in iether 'out' or 'in' within the default or predefined `--days` period then I get the 'complete' output.

**Comment by alexbosworth** [comment]
I'm not sure why this would happen if it's the same calls
