### ISSUE TITLE
Stuck in initial Telegram setup, unable to set new API token.

### ISSUE THREAD

**Issue by Aerysch** [alexbosworth/balanceofsatoshis#129]
Hello,

I've initiate the setup and pasted the API token, since that I am only getting the following error message and was not able to figure out how I would reset / set a new token.
I guess I messed up pasting the token somehow.

Message:
```
connecting_to_telegram:
  (empty array)
? Connection code? (Bot command: /connect) (node:5918) UnhandledPromiseRejectionWarning: Error: 401: Unauthorized: invalid token specified
    at Telegram.callApi (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/core/network/client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5918) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5918) UnhandledPromiseRejectionWarning: Error: 401: Unauthorized: invalid token specified
    at Telegram.callApi (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/core/network/client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Telegraf.launch (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/telegraf.js:95:78)
(node:5918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
? Connection code? (Bot command: /connect) NaN
```

Help is much appreciated.
Cheers

**Comment by Aerysch** [comment]
Was able to solve it by removing the api key file
`rm ~/.bos/telegram_bot_api_key`

**Comment by alexbosworth** [comment]
There is also a telegram option `--reset-api-key` that will allow restarting from scratch
