### ISSUE TITLE
bos can't connect to default 0.14 lnd

### ISSUE THREAD

**Issue by darthginger** [alexbosworth/balanceofsatoshis#141]
bos 11.12.1
lnd 0.14.1
bos can't connect to lnd that uses default rpc and macaroon+cert locations anymore after upgrading to 0.14.1 from 0.13.4
If i use a credentials.json and --node the commands work.
My credentials json with default paths:
```
{
  "cert_path": "/home/bitcoin/.lnd/tls.cert",
  "macaroon_path": "/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon",
  "socket": "localhost:10009"
}
```
It worked without a credentials.json before the upgrade to lnd 0.14+
This is the error from bos peers other commands return similar errors:
```
err:
  - 503
  - UnexpectedGetPeersError
  -
    err:
      message: 14 UNAVAILABLE: No connection established
      stack:
        - Error: 14 UNAVAILABLE: No connection established
        -     at Object.callErrorFromStatus (/home/bitcoin/.nvm/versions/node/v16.13.0/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        -     at Object.onReceiveStatus (/home/bitcoin/.nvm/versions/node/v16.13.0/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
        -     at Object.onReceiveStatus (/home/bitcoin/.nvm/versions/node/v16.13.0/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        -     at Object.onReceiveStatus (/home/bitcoin/.nvm/versions/node/v16.13.0/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        -     at /home/bitcoin/.nvm/versions/node/v16.13.0/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
        -     at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
Maybe it has something to do with tor.skip-proxy-for-clearnet-targets ? I use that option with my lnd

**Comment by alexbosworth** [comment]
it would look in the default locations so probably the issue is there is some custom hostname and that confuses it

**Comment by loffelmacher** [comment]
Ah, that has improved the situation, `bos nodes` giving sensible output now, the other command is not though. Here's `bos nodes`

```
bos@raspberrypi:~ $ bos nodes --verbose
(node:3430658) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)

nodes: 
  - 
    is_online:  true
    node_name:  the0ther
    public_key: 03590bc434aaba157588dc84XXXXXXXXXX5d7848bc10f6a564ba3248ea68e
  - 
    is_online:  true
    node_name:  the0therstore.duckdns.org
    public_key: 03590bc434aaba157588dc84b74XXXXXXXXXXXX5d7848bc10f6a564ba3248ea68e
```

**Comment by alexbosworth** [comment]
try using `bos --node the0ther chart-fees-earned --days 7`
