### ISSUE TITLE
Probing ACINQ - 503 UnexpectedErrGettingRouteToDestination - message: 2 UNKNOWN: feature pair exists

### ISSUE THREAD

**Issue by githorray** [alexbosworth/balanceofsatoshis#31]
```
$ bos --version
5.39.1

$ lnd --version
lnd version 0.10.99-beta commit=clock/v1.0.0-49-g9b8d51231c9cc5505380e911a45378f78d306190

$ bos probe --find-max 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f
checking_for_path_to: ACINQ 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f
err: 
  - 503
  - UnexpectedErrGettingRouteToDestination
  - 
    err: 
      message: 2 UNKNOWN: feature pair exists
      stack: 
        - Error: 2 UNKNOWN: feature pair exists
        -     at Object.exports.createStatusError (/usr/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/common.js:91:15)
        -     at Object.onReceiveStatus (/usr/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:1209:28)
        -     at InterceptingListener._callNext (/usr/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:568:42)
        -     at InterceptingListener.onReceiveStatus (/usr/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:618:8)
        -     at callback (/usr/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:847:24)
```

**Comment by alexbosworth** [comment]
Please check latest release to see if it solved this issue

**Comment by githorray** [comment]
Solved.
