### ISSUE TITLE
Running into a FailedToFindHomeDataDirectory

### ISSUE THREAD

**Issue by loffelmacher** [alexbosworth/balanceofsatoshis#332]
Hi, I'm running on a raspiblitz node, and was using `bos` with no trouble. I recently installed a TLS cert for a duckdns.org domain name, and now I can't seem to run `bos` anymore. I keep getting this:

```
bos@raspberrypi:~/balanceofsatoshis $ bos nodes --verbose

err: 
  - 400
  - FailedToFindHomeDataDirectory

Error
    at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@alexbosworth/caporal/lib/command.js:486:46
    at tryCatcher (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)

```

Here is my bos version info:

```
bos@raspberrypi:~/balanceofsatoshis $ bos --version
11.50.0
```

I tried out creating a new node by making a file at `~/.bos/<some-name-does-it-even-matter>/credentials.json` with the base64 cert and base64 macaroon, did not help. Tried the same using the `_path` fields in credentials.json, pointing at cert and macaroon but no dice. What else can I try out?

**Comment by alexbosworth** [comment]
Did you try removing ~/.bos dir

**Comment by loffelmacher** [comment]
Just tried that out and it seems to re-create it with nothing inside the folder.

**Comment by alexbosworth** [comment]
ok and did you add the saved node back?

**Comment by loffelmacher** [comment]
Yes, added it back too. I've tried uninstalling and re-installing as well. When I did that, it had nothing at all in `/home/bos/.bos`, then after re-install it created a `/home/bos/.bos/the0ther/credentials.json` with sensible looking contents. 

I've still got a hunch that something is wrong with my machine's name, it was initially just called `the0ther` and since setting up a BTC Pay with TLS cert, that name's changed to `the0therstore.duckdns.org`. 

As a shot in the dark I copied my `/home/bos/.bos/the0ther/` directory to `/home/bos/.bos/the0therstore.duckdns.org/`. Still no luck.

**Comment by alexbosworth** [comment]
the error is always the same as above?

**Comment by loffelmacher** [comment]
At the moment I am getting this result:

```
bos@raspberrypi:~ $ bos nodes --verbose

err: 
  - 400
  - FailedToFindHomeDataDirectory

Error
    at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@alexbosworth/caporal/lib/command.js:486:46
    at tryCatcher (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
```

my `.bos/` looks like this:

```
bos@raspberrypi:~ $ ls -R .bos/
.bos/:
the0ther  the0therstore.duckdns.org

.bos/the0ther:
credentials.json

.bos/the0therstore.duckdns.org:
credentials.json
```

Trying out a different command I get this kind of result:

```
bos@raspberrypi:~ $ bos chart-fees-earned --days 7 --verbose

err: 
  - 503
  - GetForwardingHistoryError
  - 
    err: 
      message: 14 UNAVAILABLE: No connection established
      stack: 
        - Error: 14 UNAVAILABLE: No connection established
        -     at Object.callErrorFromStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
        -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
        -     at processTicksAndRejections (node:internal/process/task_queues:78:11)

Error
    at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@alexbosworth/caporal/lib/command.js:486:46
    at tryCatcher (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
```

**Comment by alexbosworth** [comment]
For some reason it doesn't think that ~/.bos is a directory so that's why it gets that error

Is it possible there is a permissions issue

**Comment by loffelmacher** [comment]
You are correct, `~/.bos` is a symlink to `/mnt/hdd/app-data/.bos/` but it has always been like that, so I don't think the problem is with that so much.

However I did run across this other issue which I suspect is what I'm actually up against: https://github.com/alexbosworth/balanceofsatoshis/issues/141.

**Comment by alexbosworth** [comment]
Did the data directory location change?

**Comment by loffelmacher** [comment]
No that didn't change

**Comment by alexbosworth** [comment]
OK maybe it's trying to use the new TLS name but it can't reach that for some reason? is it possible to make a regular directory rather than a symlink directory at ~/.bos and use the saved nodes system?
