### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by thorie7912** [alexbosworth/balanceofsatoshis#333]
I'm running into this issue. Has anyone seen this before or know how to work around it?
I'm on the `master` branch as of 6/19/22.

```
✘-2 ~/work/balanceofsatoshis [master|✔]
[xxx@prod.xxx.xxx.io] 16:04$ bos open-balanced-channel
? Public key of the node to request a balanced open with? xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

checking_route: 
  - 738495x724x1 ★ ★ ★ ★
  - zero fee routing | CLN xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Fee rate: 0.00% (0)
  - 736346x1512x0
? Total capacity of the new channel? 3000000
? Fee rate per vbyte for the joint funding transaction? 1
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at createHash (node:crypto:133:10)
    at ripemd160 (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/bitcoinjs-lib/src/crypto.js:11:12)
    at Object.hash160 (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/bitcoinjs-lib/src/crypto.js:30:10)
    at p2wpkh (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/bitcoinjs-lib/src/payments/p2wpkh.js:108:27)
    at asyncAuto.transit (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/ln-sync/funding/reserve_transit_funds.js:101:26)
    at runTask (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:293:13)
    at /home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:233:31
    at processQueue (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:243:13)
    at taskComplete (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:259:9)
    at /home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:286:17
    at /home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at /home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/lightning/node_modules/asyncjs-util/return_result.js:26:50
    at wrapper (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/internal/once.js:12:16)
    at processQueue (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:239:20)
    at taskComplete (/home/xxx/work/node-v18.4.0-linux-x64/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:259:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
You have new mail in /var/mail/xxx
✘-1 ~/work/balanceofsatoshis [master|✔] 
[xxx@prod.xxx.xxx.io] 16:05$ 

```

**Comment by alexbosworth** [comment]
try node 16

**Comment by thorie7912** [comment]
That worked, thank you.

**Comment by alexbosworth** [comment]
node 18 should work now
