### ISSUE TITLE
[remove-peer] Unexpected Error

### ISSUE THREAD

**Issue by hieblmi** [alexbosworth/balanceofsatoshis#336]
Closing a channel with 1 sat/vbyte caused the following exception but the channel closing still went through. If `unable to process close msg: couldn't find compromise fee` is part of the protocol then maybe pretty printing it would make more sense.
```
:~$ bos remove-peer 03d607f3e69fd111524a867b288216bfab263b6e1114e07783799a6fe29bb84fac --fee-rate 1

close_with_peer: 
  alias:              xxx
  first_connected:    5 days ago
  last_activity:      5 days ago
  inbound_fee_rate:   0.10% (1000)
  outbound_liquidity: xxx
  public_key:         333
channels_to_close: 
  - xxx
fee_rate:          1

err: 
  - 503
  - UnexpectedErrorClosingChannel
  - 
    err: 
      - 503
      - UnexpectedCloseChannelError
      - 
        err: 
          message: 2 UNKNOWN: unable to process close msg: couldn't find compromise fee
          stack: 
            - Error: 2 UNKNOWN: unable to process close msg: couldn't find compromise fee
            -     at Object.callErrorFromStatus (/home/xxx/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
            -     at Object.onReceiveStatus (/home/xxx/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client.js:349:49)
            -     at Object.onReceiveStatus (/home/xxx/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
            -     at /home/xxx/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
            -     at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by alexbosworth** [comment]
did it close cooperatively?

**Comment by hieblmi** [comment]
Not for the time I was waiting - I ended up force closing the channel.

**Comment by alexbosworth** [comment]
ah ok so instead of the raw error message from lnd you would want a different error message

**Comment by hieblmi** [comment]
I think a more detailed explanation of the error would help users understand the flow. Instead of `couldn't find compromise fee` maybe it makes sense to improve the error message in lnd.
Without knowing the exact flow maybe something user friendly like: "The channel closing failed as our node couldn't negotiate a closing fee with the remote party. The next steps you could take are...."

**Comment by alexbosworth** [comment]
yeah I think this could potentially be handled at the LND side
