### ISSUE TITLE
probe failure on inactive node - TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by githorray** [alexbosworth/balanceofsatoshis#35]
$ bos --version
5.39.2

$ lnd --version
lnd version 0.10.99-beta commit=clock/v1.0.0-71-g87880c0d56937f2380acee37910492b2fc7b910f

$ lncli getnodeinfo <inactive_node_pub_key>
[lncli] rpc error: code = Unknown desc = unable to find node

$ bos probe <inactive_node_pub_key>
/usr/lib/node_modules/balanceofsatoshis/network/probe_destination.js:164
      return cbk(null, {features: features.filter(n => !!n.is_known)});
                                           ^

TypeError: Cannot read property 'filter' of undefined
    at asyncAuto.getFeatures (/usr/lib/node_modules/balanceofsatoshis/network/probe_destination.js:164:44)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at /usr/lib/node_modules/balanceofsatoshis/network/probe_destination.js:139:18
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/asyncjs-util/return_result.js:22:40
    at wrapper (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/once.js:12:16)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:217:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/ln-service/node_modules/lightning/lnd_methods/info/get_node.js:91:20
    at Object.onReceiveStatus (/usr/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:1210:9)
    at InterceptingListener._callNext (/usr/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/usr/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:618:8)

**Comment by alexbosworth** [comment]
Ah thanks for this report, regression from the fix for probing acinq :(

**Comment by alexbosworth** [comment]
This should be fixed in 5.39.3

**Comment by githorray** [comment]
Fixed.
