### ISSUE TITLE
[telegram] bot stopped to respond after /invoice command was send

### ISSUE THREAD

**Issue by ChuckNorrison** [alexbosworth/balanceofsatoshis#412]
After /invoice without any arguments was send via telegram, the current bot version 12.35.1 stops to respond on any command till it gets restarted. After restart, i get some logs

> Sep 25 20:54:14 raspberrypi bos[1824061]: connecting_to_telegram:
> Sep 25 20:54:14 raspberrypi bos[1824061]:   (empty array)
> Sep 25 20:54:47 raspberrypi bos[1824061]: is_connected: true
> Sep 25 20:54:49 raspberrypi bos[1824061]: err:
> Sep 25 20:54:49 raspberrypi bos[1824061]:   message: Call to 'deleteMessage' failed! (400: Bad Request: message to delete not found)
> Sep 25 20:54:49 raspberrypi bos[1824061]:   stack:
> Sep 25 20:54:49 raspberrypi bos[1824061]:     - GrammyError: Call to 'deleteMessage' failed! (400: Bad Request: message to delete not found)
> Sep 25 20:54:49 raspberrypi bos[1824061]:     -     at toGrammyError (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/core/error.js:35:12)
> Sep 25 20:54:49 raspberrypi bos[1824061]:     -     at ApiClient.callApi (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/core/client.js:86:48)
> Sep 25 20:54:49 raspberrypi bos[1824061]:     -     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> Sep 25 20:54:49 raspberrypi bos[1824061]:     -     at async asyncAuto.removeMessage (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-telegram/commands/handle_invoice_command.js:83:52)

My node is currently syncing, maybe this helps

**Comment by alexbosworth** [comment]
OK I'll take a look

**Comment by alexbosworth** [comment]
Try again on the newest version?

**Comment by ChuckNorrison** [comment]
> Try again on the newest version?

The deleteMessage error is gone in the log, but its still not responding to any commands. I dont get any logs related to that event.

**Comment by alexbosworth** [comment]
Hmm maybe try making a new bot, I think it potentially got into a bad state with the issue before and I'm not sure what is wrong without a log event

**Comment by ChuckNorrison** [comment]
> Hmm maybe try making a new bot, I think it potentially got into a bad state with the issue before and I'm not sure what is wrong without a log event

i will wait my sync progress, maybe its related to the syncing of my bitcoind and lnd

**Comment by ChuckNorrison** [comment]
Tested to delete the bot and created a new bot. This worked till i executed the `/invoice` command via telegram. The message got deleted and bot stopped responding. Even a restart cant fix it.

So it seems the bot tries to create an invoice from the empty string. Maybe this could be solved by checking the arguments and verify some arguments are set to the command.

**Comment by alexbosworth** [comment]
Invoice from empty string should be supported, it will make a zero value invoice

**Comment by alexbosworth** [comment]
Creating an empty invoice works on my telegram so maybe it is related to backing lnd not sync'ed

**Comment by ChuckNorrison** [comment]
ok thanks for your reply. i will get you an update after my sync is done.

**Comment by ChuckNorrison** [comment]
iam still syncing, but my telegram resumed to respond. I observed a crash log for this event:

> Sep 28 01:08:09 raspberrypi systemd[1]: Started Balance of Satoshis Telegram Bot.
> Sep 28 01:08:32 raspberrypi bos[1647775]: connecting_to_telegram:
> Sep 28 01:08:32 raspberrypi bos[1647775]:   (empty array)
> Sep 28 01:08:56 raspberrypi bos[1647775]: is_connected: true
> Sep 28 02:38:59 raspberrypi bos[1647775]: /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/telegram/start_telegram_bot.js:753
> Sep 28 02:38:59 raspberrypi bos[1647775]:             return cbk([503, 'InvoicesSubscriptionFailed', {err, from}]);
> Sep 28 02:38:59 raspberrypi bos[1647775]:                                                                  ^
> Sep 28 02:38:59 raspberrypi bos[1647775]: ReferenceError: from is not defined
> Sep 28 02:38:59 raspberrypi bos[1647775]:     at EventEmitter.<anonymous> (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/telegram/start_telegram_bot.js:753:66)
> Sep 28 02:38:59 raspberrypi bos[1647775]:     at EventEmitter.emit (node:events:526:28)
> Sep 28 02:38:59 raspberrypi bos[1647775]:     at finished (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/lightning/lnd_methods/invoices/subscribe_to_invoices.js:106:22)
> Sep 28 02:38:59 raspberrypi bos[1647775]:     at ClientReadableStreamImpl.<anonymous> (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/lightning/lnd_methods/invoices/subscribe_to_invoices.js:158:34)
> Sep 28 02:38:59 raspberrypi bos[1647775]:     at ClientReadableStreamImpl.emit (node:events:526:28)
> Sep 28 02:38:59 raspberrypi bos[1647775]:     at endReadableNT (node:internal/streams/readable:1345:12)
> Sep 28 02:38:59 raspberrypi bos[1647775]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> Sep 28 02:38:59 raspberrypi systemd[1]: bos-telegram.service: Main process exited, code=exited, status=1/FAILURE

**Comment by alexbosworth** [comment]
OK I'll look at that crash

**Comment by alexbosworth** [comment]
Should be fixed now

**Comment by ChuckNorrison** [comment]
`lncli addinvoice` hangs and does not respond. This should be related to the sync state of my node.

**Comment by alexbosworth** [comment]
I'd guess that's why the /invoice command also doesn't respond, it's waiting for a response from LND that isn't coming

**Comment by ChuckNorrison** [comment]
Maybe a typing state could be great as loading animation, what do you think? 

`replyWithChatAction('typing')`

The command is still running, a timeout 120s could increase usability in this circumstance a lot
