### ISSUE TITLE
limit-forwarding after update 0.15.4

### ISSUE THREAD

**Issue by mark0st83** [alexbosworth/balanceofsatoshis#428]
Hey everyone,

I've recently updated LND on 0.15.4. Before that I have limited my forwards with BOS. But after the update this isn't possible any more.
I've checked this because after the Update there where no more forwardings in LND. I should stop BOS before stopping and updating LND.

So this was my first Checkup.

```
bos limit-forwarding --max-hours-since-last-block 1

limiting_forwards: true

err: 
  - 503
  - UnexpectedErrorLimitingForwarding
  - 
    err: 
      - 503
      - UnexpectedErrorInForwardInterceptor
      - 
        err: 
          message: 2 UNKNOWN: interceptor already exists
          stack: 
            - Error: 2 UNKNOWN: interceptor already exists
            -     at Object.callErrorFromStatus (/home/bos/balanceofsatoshis/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
            -     at Object.onReceiveStatus (/home/bos/balanceofsatoshis/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:422:49)
            -     at Object.onReceiveStatus (/home/bos/balanceofsatoshis/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
            -     at /home/bos/balanceofsatoshis/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
            -     at processTicksAndRejections (node:internal/process/task_queues:78:11)
            - for call at
            -     at ServiceClientImpl.makeBidiStreamRequest (/home/bos/balanceofsatoshis/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:406:34)
            -     at ServiceClientImpl.<anonymous> (/home/bos/balanceofsatoshis/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
            -     at module.exports (/home/bos/balanceofsatoshis/node_modules/ln-sync/node_modules/lightning/lnd_methods/offchain/subscribe_to_forward_requests.js:59:32)
            -     at module.exports (/home/bos/balanceofsatoshis/node_modules/ln-sync/monitor/enforce_forward_request_rules.js:144:30)
            -     at asyncAuto.limit (/home/bos/balanceofsatoshis/peers/limit_forwarding.js:93:21)
            -     at runTask (/home/bos/balanceofsatoshis/node_modules/async/auto.js:293:13)
            -     at /home/bos/balanceofsatoshis/node_modules/async/auto.js:233:31
            -     at processQueue (/home/bos/balanceofsatoshis/node_modules/async/auto.js:243:13)
            -     at taskComplete (/home/bos/balanceofsatoshis/node_modules/async/auto.js:259:9)
            -     at /home/bos/balanceofsatoshis/node_modules/async/auto.js:286:17
            -     at /home/bos/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
            -     at asyncAuto.onlyAllow (/home/bos/balanceofsatoshis/peers/limit_forwarding.js:74:18)
            -     at runTask (/home/bos/balanceofsatoshis/node_modules/async/auto.js:293:13)
            -     at /home/bos/balanceofsatoshis/node_modules/async/auto.js:233:31
            -     at processQueue (/home/bos/balanceofsatoshis/node_modules/async/auto.js:243:13)
            -     at taskComplete (/home/bos/balanceofsatoshis/node_modules/async/auto.js:259:9)
```

**Comment by mark0st83** [comment]
Done after update to 13.3.4 - thank you
