### ISSUE TITLE
TypeError: str.toLowerCase is not a function

### ISSUE THREAD

**Issue by benthecarman** [alexbosworth/balanceofsatoshis#434]
Got this error

```
$ bos open-balanced-channel --recover

err: 
  - 400
  - FailedToParseChainAddressToRecover
  - 
    err: 
      message: str.toLowerCase is not a function
      stack: 
        - TypeError: str.toLowerCase is not a function
        -     at __decode (/home/ben/.nvm/versions/node/v16.15.0/lib/node_modules/balanceofsatoshis/node_modules/bech32/dist/index.js:116:29)
        -     at Object.decode (/home/ben/.nvm/versions/node/v16.15.0/lib/node_modules/balanceofsatoshis/node_modules/bech32/dist/index.js:155:21)
        -     at fromBech32 (/home/ben/.nvm/versions/node/v16.15.0/lib/node_modules/balanceofsatoshis/node_modules/bitcoinjs-lib/src/address.js:59:31)
 ```

**Comment by alexbosworth** [comment]
It requires the address with funds you want to recover

You can also just use the refund tx that is displayed at the start of the flow

**Comment by alexbosworth** [comment]
Or you could try the new open group channel, it doesn't need a refund tx
