### ISSUE TITLE
Error running `bos accounting payments`

### ISSUE THREAD

**Issue by tdickman** [alexbosworth/balanceofsatoshis#5]
I am receiving the following error when attempting to run `bos accounting payments` against my node:

```
/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/node_modules/ln-service/bolt11/parse_payment_request.js:80
    throw new Error('ExpectedLnPrefix');
    ^

Error: ExpectedLnPrefix
    at module.exports (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/node_modules/ln-service/bolt11/parse_payment_request.js:80:11)
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/harmony/payments_as_records.js:40:38
    at Array.map (<anonymous>)
    at module.exports (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/harmony/payments_as_records.js:37:31)
    at asyncAuto.payments (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/report/get_accounting_report.js:238:26)
    at runTask (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/asyncjs-util/return_result.js:26:50
    at wrapper (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/once.js:12:16)
    at processQueue (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:173:20)
    at taskComplete (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
```

**Comment by alexbosworth** [comment]
Interesting, if you don't have a lot of payments can you see if any of them have a payment request value that doesn't start with "ln"?

**Comment by tdickman** [comment]
Looks like you might have already solved it, but for reference, one of my payment request values is in all caps for some reason (when I run `lncli listpayments`).

**Comment by alexbosworth** [comment]
Aha, that makes sense

**Comment by tdickman** [comment]
Not sure if you've pushed out an update, but on `5.0.6` I'm receiving a different error:

```
/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:9:32
    at asyncAuto.recordsWithFiat (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/report/get_accounting_report.js:373:18)
    at runTask (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/asyncjs-util/return_result.js:26:50
    at wrapper (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/once.js:12:16)
    at processQueue (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:173:20)
    at taskComplete (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/fiat/get_fiat_values.js:87:18
    at /home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/map.js:27:9
```

**Comment by alexbosworth** [comment]
I pushed another update, but this may be a new issue

Have you tried changing `--rate-provider`?

**Comment by tdickman** [comment]
Just tried changing it to `coincap` and `coindesk`, but they both return that same error.

**Comment by alexbosworth** [comment]
It's only for payments or everything else?

**Comment by tdickman** [comment]
This error only occurs for payments. All other subcommands work.

**Comment by alexbosworth** [comment]
What if you specify a month? Is there a specific month where it happens, like the month that has the uppercase payment request?

**Comment by tdickman** [comment]
It fails for November, succeeds for every other month I tried (June - October). Interestingly, the uppercase payment request is from October.

**Comment by alexbosworth** [comment]
Hmm is there any payment in November that has a weird date?

**Comment by tdickman** [comment]
Not that I can see. I ran `lncli listpayments` on my node, and I don't see anything returned that looks odd. All of the created_dates are timestamps in the right time range.

**Comment by alexbosworth** [comment]
I pushed out an update that increases coverage but I'm not sure if it will fix it

**Comment by alexbosworth** [comment]
I think I figured out what this problem was and I'm working on a fix

**Comment by alexbosworth** [comment]
I pushed out a fix, I think it should work now
