### ISSUE TITLE
`bos increase-inbound-liquidity --address <address>` error

### ISSUE THREAD

**Issue by githorray** [alexbosworth/balanceofsatoshis#50]
$ bos --version
5.41.3

$ lnd --version
lnd version 0.10.99-beta commit=clock/v1.0.0-229-ge64e71d86dc1ac716c30a80f85a22e8fb544697f

```
/usr/lib/node_modules/balanceofsatoshis/node_modules/probing/graph/max_htlc_across_route.js:29
      return BigInt(policy.max_htlc_mtokens);
             ^
TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/probing/graph/max_htlc_across_route.js:29:14
    at Array.map (<anonymous>)
    at module.exports (/usr/lib/node_modules/balanceofsatoshis/node_modules/probing/graph/max_htlc_across_route.js:26:6)
    at asyncAuto.findMax (/usr/lib/node_modules/balanceofsatoshis/node_modules/probing/routing/find_max_payable.js:123:26)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/asyncjs-util/return_result.js:26:50
    at wrapper (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/once.js:12:16)
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:173:20)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
```

Will attempt `--max-paths 1` workaround.

**Comment by alexbosworth** [comment]
I think this should be solved now
