### ISSUE TITLE
Missing swap recovery argument leads to error.

### ISSUE THREAD

**Issue by githorray** [alexbosworth/balanceofsatoshis#51]
$ bos --version
5.41.3

$ lnd --version
lnd version 0.10.99-beta commit=clock/v1.0.0-229-ge64e71d86dc1ac716c30a80f85a22e8fb544697f

$ node --version
v14.6.0

$ bos increase-inbound-liquidity --show-raw-recovery --recovery

```
(node:28266) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type boolean (true)
    at Function.from (buffer.js:329:9)
    at asyncAuto.recovery (/usr/lib/node_modules/balanceofsatoshis/node_modules/goldengate/lightninglabs/decode_swap_recovery.js:44:35)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at validate (/usr/lib/node_modules/balanceofsatoshis/node_modules/goldengate/lightninglabs/decode_swap_recovery.js:39:16)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:229:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at auto (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:164:5)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/goldengate/lightninglabs/decode_swap_recovery.js:32:12
    at new Promise (<anonymous>)
    at module.exports (/usr/lib/node_modules/balanceofsatoshis/node_modules/goldengate/lightninglabs/decode_swap_recovery.js:31:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28266) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alexbosworth** [comment]
You can't mix `--show-raw-recovery --recovery` - one is to show the raw recovery transactions and the other is to use the recovery secret if you have had an issue and want to restart the swap from where you left off

**Comment by githorray** [comment]
I removed `--show-raw-recovery`. The error seems the same.

$ bos increase-inbound-liquidity --recovery
```
(node:9038) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type boolean (true)
    at Function.from (buffer.js:329:9)
    at asyncAuto.recovery (/usr/lib/node_modules/balanceofsatoshis/node_modules/goldengate/lightninglabs/decode_swap_recovery.js:44:35)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at validate (/usr/lib/node_modules/balanceofsatoshis/node_modules/goldengate/lightninglabs/decode_swap_recovery.js:39:16)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:229:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at auto (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:164:5)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/goldengate/lightninglabs/decode_swap_recovery.js:32:12
    at new Promise (<anonymous>)
    at module.exports (/usr/lib/node_modules/balanceofsatoshis/node_modules/goldengate/lightninglabs/decode_swap_recovery.js:31:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9038) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
