### ISSUE TITLE
Error "Callback was already called." when trying to --broadcast-message on nostr

### ISSUE THREAD

**Issue by aphex3k** [alexbosworth/balanceofsatoshis#512]
This is using latest bos 14.0.0
```
➜  ~ bos nostr --nostr-key <redacted>

is_nostr_key_saved: true
```

Broadcasting a message fails with `Error("Callback was already called.");`

```
➜  ~ bos nostr --broadcast-message "This is a test"
/app/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /app/node_modules/async/internal/onlyOnce.js:9:32
    at asyncAuto.decrypt (/app/encryption/decrypt_with_secret.js:107:18)
    at runTask (/app/node_modules/async/auto.js:293:13)
    at /app/node_modules/async/auto.js:233:31
    at processQueue (/app/node_modules/async/auto.js:243:13)
    at taskComplete (/app/node_modules/async/auto.js:259:9)
    at /app/node_modules/async/auto.js:286:17
    at /app/node_modules/async/internal/onlyOnce.js:12:16
    at ScryptJob.<anonymous> (/app/encryption/decrypt_with_secret.js:92:18)
    at job.ondone (node:internal/crypto/scrypt:62:14)

Node.js v18.16.0
```

**Comment by aphex3k** [comment]
```
➜  ~ bos nostr --add-relay wss://puravida.nostr.land

relays_adjusted:
  - wss://puravida.nostr.land
  - wss://relay.<redacted>
  - wss://relay.<redacted>
```

I added a couple of relays prior to attempting a broadcast of course...

**Comment by aphex3k** [comment]
nevermind, I used the wrong nostr key. Using the correct secret key actually works...

**Comment by alexbosworth** [comment]
that's weird i didn't think i added this command yet

**Comment by alexbosworth** [comment]
fixing this by removing the nostr command
