### ISSUE TITLE
Error when recovering swap.

### ISSUE THREAD

**Issue by githorray** [alexbosworth/balanceofsatoshis#52]
$ bos --version
5.41.3

$ lnd --version
lnd version 0.10.99-beta commit=clock/v1.0.0-229-ge64e71d86dc1ac716c30a80f85a22e8fb544697f

$ node --version
v14.6.0

$ bos increase-inbound-liquidity --show-raw-recovery --recovery <recovery_secret> 
```
/usr/lib/node_modules/balanceofsatoshis/swaps/swap_out.js:404
        if (getLimits.max_cltv_delta < minCltvDelta) {
                      ^
TypeError: Cannot read property 'max_cltv_delta' of undefined
    at asyncAuto.getTimeout (/usr/lib/node_modules/balanceofsatoshis/swaps/swap_out.js:404:23)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at asyncAuto.getQuote (/usr/lib/node_modules/balanceofsatoshis/swaps/swap_out.js:328:18)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at asyncAuto.startHeight (/usr/lib/node_modules/balanceofsatoshis/swaps/swap_out.js:218:18)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
```

**Comment by alexbosworth** [comment]
Can you update to `5.41.4` and retry? This should be fixed now
