### ISSUE TITLE
Getting an error probing a very new node on the network

### ISSUE THREAD

**Issue by brianoflondon** [alexbosworth/balanceofsatoshis#520]
The node I'm probing is new on the network.

```
bos probe 03699579e1bc118091806b07aa26cc7994a4064b6f0040f6e4d5084ed09a793ebf 1000
/app/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /app/node_modules/async/internal/onlyOnce.js:9:32
    at asyncAuto.peers (/app/node_modules/ln-service/node_modules/lightning/lnd_methods/peers/get_peers.js:80:18)
    at runTask (/app/node_modules/async/auto.js:293:13)
    at /app/node_modules/async/auto.js:233:31
    at processQueue (/app/node_modules/async/auto.js:243:13)
    at taskComplete (/app/node_modules/async/auto.js:259:9)
    at /app/node_modules/async/auto.js:286:17
    at /app/node_modules/async/internal/onlyOnce.js:12:16
    at Object.callback (/app/node_modules/ln-service/node_modules/lightning/lnd_methods/peers/get_peers.js:71:18)
    at Object.onReceiveStatus (/app/node_modules/ln-service/node_modules/@grpc/grpc-js/build/src/client.js:187:40)
    at Object.onReceiveStatus (/app/node_modules/ln-service/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/ln-service/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/ln-service/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.16.0
```

Probing well known destinations does work:

```
bos probe 038f8f113c580048d847d6949371726653e02b928196bad310e3eda39ff61723f6 10000

checking_for_path_to: magnetron 038f8f113c580048d847d6949371726653e02b928196bad310e3eda39ff61723f6

evaluating:
  - 747058x1468x1 ★ ★ ★ ★
  - WalletOfSatoshi.com 035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226. Fee rate: 0.01% (100)
  - 787305x1612x1x0

fee:        1
latency_ms: 1253
probed:     10000
relays:
  - 035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226
  - 038f8f113c580048d847d6949371726653e02b928196bad310e3eda39ff61723f6
success:
  - 747058x1468x1
  - 787305x1612x1
  ```

**Comment by brianoflondon** [comment]
Some time later once the node has properly announced itself.

```
bos probe 03699579e1bc118091806b07aa26cc7994a4064b6f0040f6e4d5084ed09a793ebf 1000

checking_for_path_to: LOUDARTIST 03699579e1bc118091806b07aa26cc7994a4064b6f0040f6e4d5084ed09a793ebf

evaluating:
  - 762332x1535x1 ★ ★ ☆ ☆
  - ln.nicehash.com [Nicehash] 037659a0ac8eb3b8d0a720114efc861d3a940382dcfa1403746b4f8f6b2e8810ba. Fee rate: 0.11% (1148)
  - 772716x253x0x0
  - CryptoChill 03df3f0a2fd6bea5429a596461ce784c922b2981ada1af89cfefcd9ccfb16c16a7. Fee rate: 0.10% (1000)
  - 667394x1542x0x1
  - LNBiG[lnd-17/old-lnd-28] 030995c0c0217d763c2274aa6ed69a0bb85fa2f7d118f93631550f3b6219a577f5. Fee rate: 0.00% (42)
  - 788052x683x1x0

fee:        2
latency_ms: 3644
probed:     1000
relays:
  - 037659a0ac8eb3b8d0a720114efc861d3a940382dcfa1403746b4f8f6b2e8810ba
  - 03df3f0a2fd6bea5429a596461ce784c922b2981ada1af89cfefcd9ccfb16c16a7
  - 030995c0c0217d763c2274aa6ed69a0bb85fa2f7d118f93631550f3b6219a577f5
  - 03699579e1bc118091806b07aa26cc7994a4064b6f0040f6e4d5084ed09a793ebf
success:
  - 762332x1535x1
  - 772716x253x0
  - 667394x1542x0
  - 788052x683x1
  ```

**Comment by alexbosworth** [comment]
can you reproduce this on any other node where it still fails?
