### ISSUE TITLE
error when using `bos` with `watch`

### ISSUE THREAD

**Issue by githorray** [alexbosworth/balanceofsatoshis#53]
```
$ watch --version
watch from procps-ng 3.3.12

$ bos --version
5.43.2

$ watch bos forwards
```

```
/usr/lib/node_modules/balanceofsatoshis/network/get_forwards.js:238
        const isWideSize = size.get().width > wideSizeCols;
                                ^

TypeError: Cannot read property 'get' of undefined
    at asyncAuto.allForwards (/usr/lib/node_modules/balanceofsatoshis/network/get_forwards.js:238:33)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at asyncAuto.forwards (/usr/lib/node_modules/balanceofsatoshis/network/get_forwards.js:229:16)
    at runTask (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
    at processQueue (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
    at taskComplete (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
    at /usr/lib/node_modules/balanceofsatoshis/node_modules/asyncjs-util/return_result.js:26:50      
    at wrapper (/usr/lib/node_modules/balanceofsatoshis/node_modules/async/internal/once.js:12:16)

```

**Comment by alexbosworth** [comment]
Is this fixed in the latest version?

**Comment by githorray** [comment]
Sorta,

When exiting from `watch` the shell is broken. You cannot see what you are typing. I typed `bos --version` after exiting below.

```
$ watch bos forwards
$ 5.43.3
                                $
```

**Comment by alexbosworth** [comment]
What if you execute `reset` command?

**Comment by githorray** [comment]
`$ watch bos forwards && reset` works.
