### ISSUE TITLE
402 PaymentRequiredToCreateSwap

### ISSUE THREAD

**Issue by martini1992** [alexbosworth/balanceofsatoshis#55]
Hi, getting this error trying to increase inbound liquidity. I'm using a non-standard setup, running from a git clone and a credentials.json file because my cert and macaroons are in non-standard locations. I believe the base64 cert and macaroon are correct. I can see node info so I'm fairly sure the app is setup correctly. 100% of funds are in channels currently.

Just need some info on what the error (402 PaymentRequiredToCreateSwap) means and how to correct it.

**Comment by alexbosworth** [comment]
Are you on the latest version? Any additional logs?

**Comment by martini1992** [comment]
Running master I believe
The stacktrace provided by verbose doesn't seem helpful

```
Error                                                
    at Promise.resolve.catch.err (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/caporal/lib/command.js:486:46)
    at tryCatcher (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)                                                                     
    at tryOnImmediate (timers.js:676:5)                                                                   
    at processImmediate (timers.js:658:5)  
```
Can't see any log files elsewhere.

I'd post the rest of the output but not sure of what to redact.

**Comment by alexbosworth** [comment]
Ok thanks I will take a look

**Comment by martini1992** [comment]
Only place I can see a 402 being generated is in GoldenGate.

[https://github.com/alexbosworth/goldengate/blob/cae312bb2fd75b04d3c671f513a68efc31c6eb41/lightninglabs/create_swap_out.js](https://github.com/alexbosworth/goldengate/blob/cae312bb2fd75b04d3c671f513a68efc31c6eb41/lightninglabs/create_swap_out.js)
Line 141

**Comment by alexbosworth** [comment]
> Only place I can see a 402 being generated is in GoldenGate.
> 
> https://github.com/alexbosworth/goldengate/blob/cae312bb2fd75b04d3c671f513a68efc31c6eb41/lightninglabs/create_swap_out.js
> Line 141

I think this is a server issue that has been addressed, can you try again?

**Comment by martini1992** [comment]
Ok, different error now

```
err: 
  - 503
  - FailedToFindChainDeposit
  - 
    err: 
      message: UnexpectedErrInTxSubscription
      stack: 
        - Error: UnexpectedErrInTxSubscription
        -     at ClientReadableStream.sub.on.err (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/goldengate/node_modules/ln-service/chain/subscribe_to_chain_address.js:110:32)
        -     at ClientReadableStream.emit (events.js:198:13)
        -     at ClientReadableStream._emitStatusIfDone (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/grpc/src/client.js:234:12)
        -     at ClientReadableStream._receiveStatus (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/grpc/src/client.js:211:8)
        -     at Object.onReceiveStatus (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:1277:15)
        -     at InterceptingListener._callNext (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:568:42)
        -     at InterceptingListener.onReceiveStatus (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:618:8)
        -     at /home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:1033:24

Error
    at Promise.resolve.catch.err (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/caporal/lib/command.js:486:46)
    at tryCatcher (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/martin/working-directory/3rdparty/balanceofsatoshis/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by alexbosworth** [comment]
Can you tell me what build tags you used when building your LND? Does it include the `chainrpc` build tag?

**Comment by martini1992** [comment]
I don't know, I haven't explicitly set that so I assume not.
Would it just be...
`make tags="chainrpc"`
Or do I need to specify any default tags as well?

**Comment by martini1992** [comment]
Looking through the Makefile stuff, I'm seeing a default set for `make release` but nothing for `make install`

Might rebuild with `make -tags="autopilotrpc signrpc walletrpc chainrpc invoicesrpc watchtowerrpc"`
then `make install` probably with the same tags again.

**Comment by alexbosworth** [comment]
> Looking through the Makefile stuff, I'm seeing a default set for `make release` but nothing for `make install`
> 
> Might rebuild with `make -tags="autopilotrpc signrpc walletrpc chainrpc invoicesrpc watchtowerrpc"`
> then `make install` probably with the same tags again.

Yeah try with the additional tags

**Comment by martini1992** [comment]
Things seem to be working, I ran...

```
make clean
make tags="autopilotrpc signrpc walletrpc chainrpc invoicesrpc watchtowerrpc"
make install tags="autopilotrpc signrpc walletrpc chainrpc invoicesrpc watchtowerrpc"
```

If anyone from googling finds this then using `make install` the release tags aren't added automatically. The above tags are the release defaults in master at the time of posting.

**Comment by alexbosworth** [comment]
Yeah I add the tags on there: https://github.com/alexbosworth/run-lnd#install-lnd and actually they are included in the normal release binaries, just not in the plain build

**Comment by martini1992** [comment]
Cool, thanks for your help. I'll close this tomorrow if everything seems to have gone smoothly.
