### ISSUE TITLE
Problems with Rebalance

### ISSUE THREAD

**Issue by rene78** [alexbosworth/balanceofsatoshis#65]
I struggle to balance the funds of my channel with "fufundy_lightning" by circular rebalancing with "1.ln.aantonop.com".
**Does anyone know what is wrong?** It says "Failed to find path" but according to the output there are paths available.
![Unbenannt](https://user-images.githubusercontent.com/36115705/93710569-1bbfe780-fb48-11ea-8da6-21fc2da28835.png)
I use this command: `bos@raspberrypi:/home/admin $ bos rebalance --in fufundy_lightning --out 1.ln.aantonop.com -v`
This is the output:
```
outgoing_peer:
  alias:      1.ln.aantonop.com 0237fefbe8626bf888de0cad8c73630e32746a22a2c4faa91c1d9877a3826e1174
  public_key: 0237fefbe8626bf888de0cad8c73630e32746a22a2c4faa91c1d9877a3826e1174
incoming_peer:
  alias:      fufundy_lightning 03884478244578a7c8004b1eef1c94482f990b566290248f0feeaf43445b593ba8
  public_key: 03884478244578a7c8004b1eef1c94482f990b566290248f0feeaf43445b593ba8

circular_rebalance_for: renesraspi 0355d39776d677398058cd196ad40c882e6c95038e0760fee1736180a4a6e1eec9

evaluating:
  - 648672x1956x1 1.ln.aantonop.com 0237fefbe8626bf888de0cad8c73630e32746a22a2c4faa91c1d9877a3826e1174. Hop fee: 76
  - 560398x1144x0 LNBIG.com [lnd-17] 03fb822818be083e0a954db85257a2911a3d55458b8c1ea4124b157e865a836d12. Hop fee: 987
  - 642334x1986x0 fufundy_lightning 03884478244578a7c8004b1eef1c94482f990b566290248f0feeaf43445b593ba8. Hop fee: 1
confidence:    ★ ★ ☆ ☆
potential_fee: 1065

failure: TemporaryChannelFailure at 560398x1144x0 from 1.ln.aantonop.com

evaluating:
  - 648672x1956x1 1.ln.aantonop.com 0237fefbe8626bf888de0cad8c73630e32746a22a2c4faa91c1d9877a3826e1174. Hop fee: 76
  - 613725x2489x1 ln1.1sat.org 03c2b5e97173e2ff7baea106a34a165e0213b6c5148441ea97785b35a78a506299. Hop fee: 0
  - 615915x2232x1 WalletOfSatoshi.com 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c. Hop fee: 1
  - 565780x1248x0 LNBIG.com [lnd-17] 03fb822818be083e0a954db85257a2911a3d55458b8c1ea4124b157e865a836d12. Hop fee: 987
  - 642334x1986x0 fufundy_lightning 03884478244578a7c8004b1eef1c94482f990b566290248f0feeaf43445b593ba8. Hop fee: 1
confidence:    ★ ★ ☆ ☆
potential_fee: 1066

failure: TemporaryChannelFailure at 613725x2489x1 from 1.ln.aantonop.com

evaluating:
  - 648672x1956x1 1.ln.aantonop.com 0237fefbe8626bf888de0cad8c73630e32746a22a2c4faa91c1d9877a3826e1174. Hop fee: 76
  - 577921x317x1 rompert.com🔵 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b. Hop fee: 0
  - 641713x1198x0 lndalt1.zaphq.io 03b428ba4b48b524f1fa929203ddc2f0971c2077c2b89bb5b22fd83ed82ac2f7e1. Hop fee: 1
  - 648966x1584x1 WalletOfSatoshi.com 02004c625d622245606a1ea2c1c69cfb4516b703b47945a3647713c05fe4aaeb1c. Hop fee: 1
  - 565780x1248x0 LNBIG.com [lnd-17] 03fb822818be083e0a954db85257a2911a3d55458b8c1ea4124b157e865a836d12. Hop fee: 987
  - 642334x1986x0 fufundy_lightning 03884478244578a7c8004b1eef1c94482f990b566290248f0feeaf43445b593ba8. Hop fee: 1
confidence:    ★ ★ ☆ ☆
potential_fee: 1067

failure: TemporaryChannelFailure at 647986x674x0 from fufundy_lightning

err:
  - 400
  - FailedToFindPathBetweenPeers

Error
    at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/caporal/lib/command.js:486:46
    at tryCatcher (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

**Comment by alexbosworth** [comment]
If you're sending --in a peer, you need that peer to have inbound liquidity

**Comment by rene78** [comment]
Ah, understood. Thanks!
