### ISSUE TITLE
Callback was already called

### ISSUE THREAD

**Issue by apotdevin** [alexbosworth/balanceofsatoshis#84]
When using the `pay` function from `balanceofsatoshis/network` I sometimes get this error:

```
2020-11-02 17:58:04 debug [THUB]: Paying invoice with params: { max_fee: 1, max_paths: 1, out: [ [length]: 0 ] }
2020-11-02 17:58:05 info [THUB]: {
    "checking_for_path_to": "bob 0225b8ce4d89d6c3039c626cb5b93b8e77d681bdf485fc58729018ecf932ef1139"
}
/Users/potdevin/Documents/TH/thunderhub/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /Users/potdevin/Documents/TH/thunderhub/node_modules/async/internal/onlyOnce.js:9:32
    at Object.callback (/Users/potdevin/Documents/TH/thunderhub/node_modules/lightning/lnd_methods/info/get_node.js:99:20)
    at Object.onReceiveStatus (/Users/potdevin/Documents/TH/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:173:36)
    at Object.onReceiveStatus (/Users/potdevin/Documents/TH/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
    at Object.onReceiveStatus (/Users/potdevin/Documents/TH/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at /Users/potdevin/Documents/TH/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78
```

**Comment by apotdevin** [comment]
There are times when the payment goes through correctly but other times I get this

**Comment by alexbosworth** [comment]
> There are times when the payment goes through correctly but other times I get this

Are you using single path or multi path?

**Comment by apotdevin** [comment]
Single path in this case

**Comment by alexbosworth** [comment]
Out is an array of length zero is that what this means at the top?

**Comment by apotdevin** [comment]
Yeah didn't define an out channel so called the pay function with `out: []`

Testing somethings out and I get the error frequently when the final destination is a single hop away

**Comment by alexbosworth** [comment]
Does the same issue arise in probe?

**Comment by apotdevin** [comment]
Tested, yeah same error:
```
2020-11-02 18:45:18 info [THUB]: {
    "probing": "carol 020782262fd78db8f3798624ad58d38e44bb3423e82a7a733d808e6f23449d38a3"
}
/Users/potdevin/Documents/TH/thunderhub/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /Users/potdevin/Documents/TH/thunderhub/node_modules/async/internal/onlyOnce.js:9:32
    at Object.callback (/Users/potdevin/Documents/TH/thunderhub/node_modules/lightning/lnd_methods/info/get_node.js:99:20)
    at Object.onReceiveStatus (/Users/potdevin/Documents/TH/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:173:36)
```

**Comment by alexbosworth** [comment]
When you pass {lnd} did you get that from the same version of ln-service that is used by the balanceofsatoshis version?

**Comment by apotdevin** [comment]
Yeah using `"ln-service": "^50.3.0"` same as bos

**Comment by alexbosworth** [comment]
That's interesting, when you do probe it does the same error, can you show me the arguments and output more exactly for the probe call?

**Comment by apotdevin** [comment]
```
probe({
          lnd,
          logger,
          destination:
            '020782262fd78db8f3798624ad58d38e44bb3423e82a7a733d808e6f23449d38a3',
          out: [
            '020782262fd78db8f3798624ad58d38e44bb3423e82a7a733d808e6f23449d38a3',
          ],
        })
```

**Comment by apotdevin** [comment]
And the only output is this log:
```
{
    "probing": "carol 020782262fd78db8f3798624ad58d38e44bb3423e82a7a733d808e6f23449d38a3"
}
```
and then the error

**Comment by alexbosworth** [comment]
OK, when you probe, can you try specifying `max_paths: 1` and see if that makes a difference?

**Comment by apotdevin** [comment]
With `max_paths: 1`:
```
2020-11-02 18:59:01 info [THUB]: {
    "checking_for_path_to": "carol 020782262fd78db8f3798624ad58d38e44bb3423e82a7a733d808e6f23449d38a3"
}
/Users/potdevin/Documents/TH/thunderhub/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /Users/potdevin/Documents/TH/thunderhub/node_modules/async/internal/onlyOnce.js:9:32
```

**Comment by alexbosworth** [comment]
OK so I guess it dies in `execute_probe.js`, I will investigate

**Comment by alexbosworth** [comment]
I think I got it, just adding a test

**Comment by alexbosworth** [comment]
I pushed a new version, I hope the issue solved was the relevant issue

**Comment by apotdevin** [comment]
Tested and it's working! Thanks for the fix 👍
