### ISSUE TITLE
"accounting chain-receives" fails with error 503 UnexpectedGetChainTransactionsError

### ISSUE THREAD

**Issue by ghost** [alexbosworth/balanceofsatoshis#85]
Command: `bos accounting chain-receives`

Output:
```
err: 
  - 503
  - UnexpectedGetChainTransactionsError
  - 
    err: 
      message: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
      stack: 
        - Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        -     at Object.callErrorFromStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
        -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78
        -     at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Version `bos --version`:
```
7.2.7
```

**Comment by alexbosworth** [comment]
Try updating to nodejs 14?

**Comment by petrhejna** [comment]
I use Raspiblitz, so I and not confident to update it just by myself.
my version on Raspiblitz is:
```
node -v
v12.16.3
```

I have created [sister issue](https://github.com/rootzoll/raspiblitz/issues/1750) there.

**Comment by alexbosworth** [comment]
Maybe you can try again with the most recent release, I updated the grpc library but I don't know if that will help

**Comment by alexbosworth** [comment]
market is no longer supported due to the backing service discontinuing their API
